spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/mydb?characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
    redis:
      cache-null-values: false #是否缓存空值
      use-key-prefix: true #是否使用前缀(默认true)
      time-to-live: 10s  #缓存时间
      key-prefix: abc # 指定前缀(如果设置不使用前缀，则指定前缀无效)
  redis:
    host: 127.0.0.1
    port: 6379
#  cache:
#    type: ehcache #指定缓存
#    ehcache:
#      config: ehcache2.xml