#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/mydb?characterEncoding=UTF-8&useSSL=false
#    hikari:
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:~/test
    hikari:
      username: sa
      password: 123456
      driver-class-name: org.h2.Driver